# Generated by Django 3.2.14 on 2022-07-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1111-05-2'),
            preserve_default=False,
        ),
    ]
